version: '3.8'
services:
  fe-app:
    image: registry.cn-hangzhou.aliyuncs.com/linzheng_test/linzheng1:aaa
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/linzheng/mysql/meeting-room/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: linzheng99
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/linzheng/redis/meeting-room/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
