version: '3.8'
services:
  fe-user-app:
    image: registry.cn-hangzhou.aliyuncs.com/linzheng_test/linzheng2:userbbb
    ports:
      - 3005:3005
    depends_on:
      - nest-app
    restart: always
    networks:
      - common-network
  fe-app:
    image: registry.cn-hangzhou.aliyuncs.com/linzheng_test/linzheng1:aaa
    ports:
      - 80:80
    depends_on:
      - nest-app
    restart: always
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/linzheng/mysql/meeting-room/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: linzheng99
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/linzheng/redis/meeting-room/redis-data:/data
    restart: always
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/linzheng/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: linzheng 
      MINIO_ROOT_PASSWORD: linzheng99
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
